export default {
  HOME: 'Home',
  ONBOARDING_1_BODY: 'The most trusted & accurate source of market capitalizations, pricing, and cryptocurrency information.',
  ONBARDING_1_HEADING: 'Welcome to CoinMarketCap',
  ONBOARDING_2_BODY: 'The info you know and trust, in the palm of your hand. From crypto to exchange details, we’ve got it covered!',
  ONBARDING_2_HEADING: 'Take CoinMarketCap with you everywhere',
  ONBOARDING_3_BODY: "See how you're doing at any time by tracking your holdings in a simple view. Enter what you have, and watch it go!",
  ONBARDING_3_HEADING: 'Easily track & manage your crypto portfolio',
  ONBOARDING_4_BODY: "Create an account to sync all your settings across desktop & mobile; it's the most convenient way to stay up-to-date!",
  ONBARDING_4_HEADING: 'Sync portfolio & alerts across all your devices',
  LOG_IN: 'Log in',
  CREATE_ACCOUNT: 'Create an account',
  GO_TO_HOMEPAGE: 'Go to Homepage',
  SIGN_UP: 'Sign up',
  EMAIL_ADDRESS: 'Email Address',
  ENTER_EMAIL: 'Enter your email address...',
  PASSWORD: 'Password',
  ENTER_PASSWORD: 'Enter your password...',
  FORGOT_PASSWORD: 'Forgot password?',
  OR: 'Or',
  CONTINUE_GOOGLE: 'Continue with Google',
  CONTINUE_APPLE: 'Continue with Apple',
  NEW_TO_APP: 'New to CoinMarketCap? ',
  PASSWORD_MESSAGE: 'Password should contain both letters and numbers, with minimum length of 8 characters',
  ALREADY_HAVE_ACCOUNT: 'Already have an account? ',
  NEWS: "News",
  SEARCH: "Search",
  PORTFOLIO: "Portfolio",
  COMMUNITY: "Community",
  MARKETS: "Markets",
  MARKET_CAP: "Market Cap",
  PRICE: "Price",
  VOL_CHANGE_24H: "24h %",
  HASH: "#"
};
